import type { SeedQuizAnswer } from "./seedQuizAnswers";

export const bgcseMathsTopic4And5SeedQuizAnswers: SeedQuizAnswer[] = [
  { quizId: "bgcse-maths-t04-q1", questionId: "q1", answerIndex: 1, explanation: "3x = 18, so x = 6." },
  { quizId: "bgcse-maths-t04-q1", questionId: "q2", answerIndex: 2, explanation: "5x - 2x = 12 + 9, so 3x = 21 and x = 7." },
  { quizId: "bgcse-maths-t04-q1", questionId: "q3", answerIndex: 3, explanation: "8x - 12 = 20, so 8x = 32 and x = 4." },
  { quizId: "bgcse-maths-t04-q1", questionId: "q4", answerIndex: 0, explanation: "x + 5 = 21, so x = 16." },
  { quizId: "bgcse-maths-t04-q1", questionId: "q5", answerIndex: 2, explanation: "-2x = 12, so x = -6." },
  { quizId: "bgcse-maths-t04-q1", questionId: "q6", answerIndex: 1, explanation: "3x - 1 = 2x + 9, so x = 10." },
  { quizId: "bgcse-maths-t04-q1", questionId: "q7", answerIndex: 1, explanation: "Multiply both sides by 3/2: x = 14 × 3/2 = 21." },
  { quizId: "bgcse-maths-t04-q1", questionId: "q8", answerIndex: 0, explanation: "0.4x = 12, so x = 30." },

  { quizId: "bgcse-maths-t04-q2", questionId: "q1", answerIndex: 2, explanation: "5x = 22.50, so x = P4.50." },
  { quizId: "bgcse-maths-t04-q2", questionId: "q2", answerIndex: 0, explanation: "2x + 2(x + 3) = 34 gives 4x + 6 = 34, so x = 7." },
  { quizId: "bgcse-maths-t04-q2", questionId: "q3", answerIndex: 2, explanation: "3n + 5 = 41 gives 3n = 36, so n = 12." },
  { quizId: "bgcse-maths-t04-q2", questionId: "q4", answerIndex: 2, explanation: "4x + 12 = 132 gives 4x = 120, so x = P30." },
  { quizId: "bgcse-maths-t04-q2", questionId: "q5", answerIndex: 2, explanation: "If the child is x, then the father is 3x. 4x = 52, so x = 13." },
  { quizId: "bgcse-maths-t04-q2", questionId: "q6", answerIndex: 1, explanation: "n + (n + 1) = 51 gives 2n = 50, so n = 25." },
  { quizId: "bgcse-maths-t04-q2", questionId: "q7", answerIndex: 2, explanation: "P2450 - P350 = P2100. Dividing by 6 gives P350 per instalment." },
  { quizId: "bgcse-maths-t04-q2", questionId: "q8", answerIndex: 2, explanation: "x - 35 = 0.8x, so 0.2x = 35 and x = 175 litres." },

  { quizId: "bgcse-maths-t04-q3", questionId: "q1", answerIndex: 0, explanation: "Adding the equations gives 2x = 14, so x = 7 and y = 4." },
  { quizId: "bgcse-maths-t04-q3", questionId: "q2", answerIndex: 1, explanation: "From x - y = 2, y = x - 2. Substitution gives 3x = 15, so x = 5 and y = 3." },
  { quizId: "bgcse-maths-t04-q3", questionId: "q3", answerIndex: 2, explanation: "Using y = 7 - x in 3x + 2y = 18 gives x = 4 and y = 3." },
  { quizId: "bgcse-maths-t04-q3", questionId: "q4", answerIndex: 0, explanation: "Subtracting the second equation from the first gives 2x = 10, so x = 5 and y = 10." },
  { quizId: "bgcse-maths-t04-q3", questionId: "q5", answerIndex: 1, explanation: "Subtract 2(x + y = 7) from 2x + 3y = 17 to get y = 3, then x = 4." },
  { quizId: "bgcse-maths-t04-q3", questionId: "q6", answerIndex: 1, explanation: "From x + 2y = 10, x = 10 - 2y. Substitution gives y = 3 and x = 4." },
  { quizId: "bgcse-maths-t04-q3", questionId: "q7", answerIndex: 0, explanation: "From x - y = 2, x = y + 2. Substitution gives 5y = 10, so y = 2 and x = 4." },
  { quizId: "bgcse-maths-t04-q3", questionId: "q8", answerIndex: 1, explanation: "From x - y = 5, y = x - 5. Then 0.5x + x - 5 = 7, giving x = 8 and y = 3." },

  { quizId: "bgcse-maths-t04-q4", questionId: "q1", answerIndex: 2, explanation: "Let rice plates be x and stew plates be y. x + y = 52 and 18x + 25y = 1104. Solving gives x = 28." },
  { quizId: "bgcse-maths-t04-q4", questionId: "q2", answerIndex: 1, explanation: "Solving 600x + 400y = 2280 and 350x + 250y = 1365 gives x = 2.40 and y = 2.10." },
  { quizId: "bgcse-maths-t04-q4", questionId: "q3", answerIndex: 2, explanation: "The equations give pencil = P2 and pen = P7. Then 3 pencils and 2 pens cost P6 + P14 = P20." },
  { quizId: "bgcse-maths-t04-q4", questionId: "q4", answerIndex: 2, explanation: "With x adult and y child tickets, x + y = 180 and 12x + 7y = 1710. Solving gives x = 90." },
  { quizId: "bgcse-maths-t04-q4", questionId: "q5", answerIndex: 2, explanation: "Adding x + y = 46 and x - y = 12 gives 2x = 58, so the larger number is 29." },
  { quizId: "bgcse-maths-t04-q4", questionId: "q6", answerIndex: 3, explanation: "Solving 8x + 5y = 159 and 3x + 4y = 83 gives x = 13 and y = 11." },
  { quizId: "bgcse-maths-t04-q4", questionId: "q7", answerIndex: 2, explanation: "Solving 3a + 2c = 94 and 2a + 5c = 103 gives adult fare a = P24." },
  { quizId: "bgcse-maths-t04-q4", questionId: "q8", answerIndex: 1, explanation: "Let x be P2 coins and y be P5 coins. x + y = 40 and 2x + 5y = 128, giving y = 16." },

  { quizId: "bgcse-maths-t05-q1", questionId: "q1", answerIndex: 0, explanation: "x² - 7x + 12 = (x - 3)(x - 4), so x = 3 or 4." },
  { quizId: "bgcse-maths-t05-q1", questionId: "q2", answerIndex: 1, explanation: "x² + 5x + 6 = (x + 2)(x + 3), so x = -2 or -3." },
  { quizId: "bgcse-maths-t05-q1", questionId: "q3", answerIndex: 1, explanation: "2x² - 7x + 3 = (2x - 1)(x - 3), so x = 1/2 or 3." },
  { quizId: "bgcse-maths-t05-q1", questionId: "q4", answerIndex: 2, explanation: "x² = 49 gives x = ±7." },
  { quizId: "bgcse-maths-t05-q1", questionId: "q5", answerIndex: 1, explanation: "x² - 9x + 20 = (x - 4)(x - 5), so x = 4 or 5." },
  { quizId: "bgcse-maths-t05-q1", questionId: "q6", answerIndex: 0, explanation: "3x² - 12x = 3x(x - 4), so x = 0 or 4." },
  { quizId: "bgcse-maths-t05-q1", questionId: "q7", answerIndex: 1, explanation: "x² + 2x - 15 = (x + 5)(x - 3), so x = -5 or 3." },
  { quizId: "bgcse-maths-t05-q1", questionId: "q8", answerIndex: 0, explanation: "Using the quadratic formula gives x = (-3 ± √65)/4, so x ≈ 1.27 or -2.77." },

  { quizId: "bgcse-maths-t05-q2", questionId: "q1", answerIndex: 0, explanation: "60/v - 60/(v + 5) = 1. Clearing denominators gives v² + 5v - 300 = 0." },
  { quizId: "bgcse-maths-t05-q2", questionId: "q2", answerIndex: 1, explanation: "v² + 5v - 300 = (v + 20)(v - 15). The valid v is 15, so the faster cyclist travels at 20 km/h." },
  { quizId: "bgcse-maths-t05-q2", questionId: "q3", answerIndex: 0, explanation: "180/v - 180/(v + 6) = 1. Clearing denominators gives v² + 6v - 1080 = 0." },
  { quizId: "bgcse-maths-t05-q2", questionId: "q4", answerIndex: 2, explanation: "v² + 6v - 1080 = (v + 36)(v - 30). The small pump rate is 30, so the larger pump rate is 36 L/min." },
  { quizId: "bgcse-maths-t05-q2", questionId: "q5", answerIndex: 0, explanation: "Area = x(x + 4) = 96, so x² + 4x - 96 = 0." },
  { quizId: "bgcse-maths-t05-q2", questionId: "q6", answerIndex: 1, explanation: "x² + 4x - 96 = (x + 12)(x - 8). A width cannot be negative, so x = 8 cm." },
  { quizId: "bgcse-maths-t05-q2", questionId: "q7", answerIndex: 0, explanation: "n(n + 1) = 156 expands to n² + n - 156 = 0." },
  { quizId: "bgcse-maths-t05-q2", questionId: "q8", answerIndex: 1, explanation: "n² + n - 156 = (n + 13)(n - 12). The positive smaller integer is 12." },
];
