import type { SeedQuizAnswer } from "./seedQuizAnswers";

export const bgcseMathsTopic9To11SeedQuizAnswers: SeedQuizAnswer[] = [
  { quizId: "bgcse-maths-t09-q1", questionId: "q1", answerIndex: 1, explanation: "Average speed = 180 ÷ 3 = 60 km/h." },
  { quizId: "bgcse-maths-t09-q1", questionId: "q2", answerIndex: 2, explanation: "72 km/h ÷ 3.6 = 20 m/s." },
  { quizId: "bgcse-maths-t09-q1", questionId: "q3", answerIndex: 1, explanation: "Distance = 8 × 75 = 600 m." },
  { quizId: "bgcse-maths-t09-q1", questionId: "q4", answerIndex: 1, explanation: "Speed = 400 ÷ 50 = 8 m/s." },
  { quizId: "bgcse-maths-t09-q1", questionId: "q5", answerIndex: 1, explanation: "Time = 150 ÷ 60 = 2.5 h." },
  { quizId: "bgcse-maths-t09-q1", questionId: "q6", answerIndex: 1, explanation: "Rate = 240 ÷ 8 = 30 L/min." },
  { quizId: "bgcse-maths-t09-q1", questionId: "q7", answerIndex: 2, explanation: "360 ÷ 6 = 60 boxes/h, so 9 h gives 540 boxes." },
  { quizId: "bgcse-maths-t09-q1", questionId: "q8", answerIndex: 2, explanation: "Average speed is distance divided by time." },

  { quizId: "bgcse-maths-t09-q2", questionId: "q1", answerIndex: 2, explanation: "A horizontal distance-time section means distance is unchanged, so the object is stationary." },
  { quizId: "bgcse-maths-t09-q2", questionId: "q2", answerIndex: 1, explanation: "Gradient of a speed-time graph is change in speed divided by change in time: acceleration." },
  { quizId: "bgcse-maths-t09-q2", questionId: "q3", answerIndex: 1, explanation: "Area under a speed-time graph gives distance travelled." },
  { quizId: "bgcse-maths-t09-q2", questionId: "q4", answerIndex: 0, explanation: "Acceleration = (16 - 4) ÷ 6 = 2 m/s²." },
  { quizId: "bgcse-maths-t09-q2", questionId: "q5", answerIndex: 2, explanation: "Distance = 12 × 25 = 300 m." },
  { quizId: "bgcse-maths-t09-q2", questionId: "q6", answerIndex: 0, explanation: "Triangle area = 1/2 × 20 × 15 = 150 m." },
  { quizId: "bgcse-maths-t09-q2", questionId: "q7", answerIndex: 1, explanation: "Acceleration = (5 - 20) ÷ 3 = -5 m/s²." },
  { quizId: "bgcse-maths-t09-q2", questionId: "q8", answerIndex: 0, explanation: "A straight sloping distance-time line has constant gradient, so constant speed." },

  { quizId: "bgcse-maths-t09-q3", questionId: "q1", answerIndex: 0, explanation: "Acceleration = (11.0 - 14.5) ÷ 12 = -0.2917 m/s², or -0.292 m/s²." },
  { quizId: "bgcse-maths-t09-q3", questionId: "q2", answerIndex: 1, explanation: "Distance = 11 × 45 = 495 m." },
  { quizId: "bgcse-maths-t09-q3", questionId: "q3", answerIndex: 1, explanation: "Average speed during uniform acceleration is (10 + 18)/2 = 14 m/s, so distance = 14 × 8 = 112 m." },
  { quizId: "bgcse-maths-t09-q3", questionId: "q4", answerIndex: 0, explanation: "0.6 min = 0.01 h, so distance = 80 × 0.01 = 0.8 km." },
  { quizId: "bgcse-maths-t09-q3", questionId: "q5", answerIndex: 1, explanation: "1005 ÷ 85 = 11.8235..., so 11.8 m/s to 3 s.f." },
  { quizId: "bgcse-maths-t09-q3", questionId: "q6", answerIndex: 1, explanation: "Time = 900 ÷ 15 = 60 s." },
  { quizId: "bgcse-maths-t09-q3", questionId: "q7", answerIndex: 1, explanation: "Rectangle = 40 × 9 = 360 m and triangle = 1/2 × 10 × 9 = 45 m, total 405 m." },
  { quizId: "bgcse-maths-t09-q3", questionId: "q8", answerIndex: 1, explanation: "42/1.5 = 28 km/h and 42/1.75 = 24 km/h, a decrease of 4 km/h." },

  { quizId: "bgcse-maths-t10-q1", questionId: "q1", answerIndex: 1, explanation: "A compass and straightedge produce the equal arcs needed for a perpendicular bisector." },
  { quizId: "bgcse-maths-t10-q1", questionId: "q2", answerIndex: 1, explanation: "7.5 × 10 = 75 m." },
  { quizId: "bgcse-maths-t10-q1", questionId: "q3", answerIndex: 1, explanation: "The perpendicular bisector crosses a segment at its midpoint, 4 cm from A." },
  { quizId: "bgcse-maths-t10-q1", questionId: "q4", answerIndex: 1, explanation: "An angle bisector divides an angle into two equal angles." },
  { quizId: "bgcse-maths-t10-q1", questionId: "q5", answerIndex: 1, explanation: "Bearings are measured clockwise from north." },
  { quizId: "bgcse-maths-t10-q1", questionId: "q6", answerIndex: 2, explanation: "4.2 × 20 = 84 km." },
  { quizId: "bgcse-maths-t10-q1", questionId: "q7", answerIndex: 0, explanation: "Arcs of radius 5 cm and 6 cm from the base endpoints locate the third vertex." },
  { quizId: "bgcse-maths-t10-q1", questionId: "q8", answerIndex: 2, explanation: "30 m at 10 m per cm is 3 cm." },

  { quizId: "bgcse-maths-t10-q2", questionId: "q1", answerIndex: 1, explanation: "Points a fixed distance from P form a circle centred at P." },
  { quizId: "bgcse-maths-t10-q2", questionId: "q2", answerIndex: 2, explanation: "All points equidistant from A and B lie on the perpendicular bisector of AB." },
  { quizId: "bgcse-maths-t10-q2", questionId: "q3", answerIndex: 0, explanation: "Points equidistant from two intersecting lines lie on their angle bisectors." },
  { quizId: "bgcse-maths-t10-q2", questionId: "q4", answerIndex: 1, explanation: "A fixed perpendicular distance from a line gives two lines parallel to it, one on each side." },
  { quizId: "bgcse-maths-t10-q2", questionId: "q5", answerIndex: 0, explanation: "Both conditions are met where the circle about P intersects the perpendicular bisector of AB." },
  { quizId: "bgcse-maths-t10-q2", questionId: "q6", answerIndex: 0, explanation: "Exactly 3.8 km from S means a circle centred at S with radius 3.8 km." },
  { quizId: "bgcse-maths-t10-q2", questionId: "q7", answerIndex: 0, explanation: "Within 2 cm of a boundary line is the strip between the boundary and a parallel line 2 cm inside." },
  { quizId: "bgcse-maths-t10-q2", questionId: "q8", answerIndex: 1, explanation: "Equal distance from A and D gives their perpendicular bisector; exactly 6 cm from D gives a circle centred at D." },

  { quizId: "bgcse-maths-t11-q1", questionId: "q1", answerIndex: 0, explanation: "Add the translation vector: (2+3, -1+4) = (5,3)." },
  { quizId: "bgcse-maths-t11-q1", questionId: "q2", answerIndex: 1, explanation: "Reflection in the x-axis changes the sign of y: (4,-2) → (4,2)." },
  { quizId: "bgcse-maths-t11-q1", questionId: "q3", answerIndex: 0, explanation: "Reflection in the y-axis changes the sign of x: (-3,5) → (3,5)." },
  { quizId: "bgcse-maths-t11-q1", questionId: "q4", answerIndex: 1, explanation: "Reflection in y = x swaps the coordinates: (2,7) → (7,2)." },
  { quizId: "bgcse-maths-t11-q1", questionId: "q5", answerIndex: 1, explanation: "A 90° anticlockwise rotation maps (x,y) to (-y,x), giving (-1,3)." },
  { quizId: "bgcse-maths-t11-q1", questionId: "q6", answerIndex: 0, explanation: "A 180° rotation maps (x,y) to (-x,-y), giving (2,-5)." },
  { quizId: "bgcse-maths-t11-q1", questionId: "q7", answerIndex: 2, explanation: "A translation moves every point by the same vector." },
  { quizId: "bgcse-maths-t11-q1", questionId: "q8", answerIndex: 0, explanation: "A rotation is fully specified by centre, angle and direction." },

  { quizId: "bgcse-maths-t11-q2", questionId: "q1", answerIndex: 0, explanation: "Scale factor 2 about the origin doubles both coordinates: (4,6)." },
  { quizId: "bgcse-maths-t11-q2", questionId: "q2", answerIndex: 1, explanation: "Scale factor -1 about the origin maps (-4,2) to (4,-2)." },
  { quizId: "bgcse-maths-t11-q2", questionId: "q3", answerIndex: 2, explanation: "Area scale factor is the square of the length scale factor: 3² = 9." },
  { quizId: "bgcse-maths-t11-q2", questionId: "q4", answerIndex: 1, explanation: "10 × 1/2 = 5 cm." },
  { quizId: "bgcse-maths-t11-q2", questionId: "q5", answerIndex: 1, explanation: "Multiply both coordinates by -2: (1,-3) → (-2,6)." },
  { quizId: "bgcse-maths-t11-q2", questionId: "q6", answerIndex: 1, explanation: "From C to A is (4,4); from C to A' is (8,8), so the scale factor is 2." },
  { quizId: "bgcse-maths-t11-q2", questionId: "q7", answerIndex: 0, explanation: "Two transformations applied in sequence form a combined transformation." },
  { quizId: "bgcse-maths-t11-q2", questionId: "q8", answerIndex: 2, explanation: "Enlargement preserves angle size and shape, though lengths and areas change." },

  { quizId: "bgcse-maths-t11-q3", questionId: "q1", answerIndex: 1, explanation: "A square has four lines of symmetry." },
  { quizId: "bgcse-maths-t11-q3", questionId: "q2", answerIndex: 2, explanation: "A regular hexagon matches itself six times in a full turn." },
  { quizId: "bgcse-maths-t11-q3", questionId: "q3", answerIndex: 1, explanation: "A non-square rectangle matches itself twice in a full rotation: at 0° and 180°." },
  { quizId: "bgcse-maths-t11-q3", questionId: "q4", answerIndex: 1, explanation: "(-4,0) + (3,-5) = (-1,-5)." },
  { quizId: "bgcse-maths-t11-q3", questionId: "q5", answerIndex: 1, explanation: "A 90° clockwise rotation maps (x,y) to (y,-x), giving (4,-1)." },
  { quizId: "bgcse-maths-t11-q3", questionId: "q6", answerIndex: 0, explanation: "The line x=2 is midway between x=5 and its image, so x' = -1 while y stays -1." },
  { quizId: "bgcse-maths-t11-q3", questionId: "q7", answerIndex: 1, explanation: "From centre (-1,1) to (2,3) is (3,2). Doubling gives (6,4), so the image is (5,5)." },
  { quizId: "bgcse-maths-t11-q3", questionId: "q8", answerIndex: 0, explanation: "A reflection is an isometry: lengths and angles are preserved, but orientation is reversed." },
];
