import type { SeedQuizAnswer } from "./seedQuizAnswers";

export const bgcseMathsTopic12To15SeedQuizAnswers: SeedQuizAnswer[] = [
  { quizId: "bgcse-maths-t12-q1", questionId: "q1", answerIndex: 0, explanation: "AB = B - A = (7 - 2, 3 - (-1)) = (5, 4)." },
  { quizId: "bgcse-maths-t12-q1", questionId: "q2", answerIndex: 1, explanation: "Magnitude = √(6² + 8²) = √100 = 10." },
  { quizId: "bgcse-maths-t12-q1", questionId: "q3", answerIndex: 2, explanation: "AB = OB - OA = b - a." },
  { quizId: "bgcse-maths-t12-q1", questionId: "q4", answerIndex: 0, explanation: "Add corresponding components: (−3 + 7, 5 − 2) = (4, 3)." },
  { quizId: "bgcse-maths-t12-q1", questionId: "q5", answerIndex: 1, explanation: "Multiply each component by 2 to get (8, −2)." },
  { quizId: "bgcse-maths-t12-q1", questionId: "q6", answerIndex: 1, explanation: "PQ = Q - P = (3 - (-2), -1 - 4) = (5, -5)." },
  { quizId: "bgcse-maths-t12-q1", questionId: "q7", answerIndex: 1, explanation: "The midpoint position vector is the average of the endpoint position vectors: (a + b)/2." },
  { quizId: "bgcse-maths-t12-q1", questionId: "q8", answerIndex: 0, explanation: "Parallel vectors are scalar multiples. (6, −8) = 2(3, −4)." },

  { quizId: "bgcse-maths-t12-q2", questionId: "q1", answerIndex: 2, explanation: "AC = OC - OA = m - k." },
  { quizId: "bgcse-maths-t12-q2", questionId: "q2", answerIndex: 1, explanation: "AB is 4/3 as long as OC, so AB = 4m/3." },
  { quizId: "bgcse-maths-t12-q2", questionId: "q3", answerIndex: 0, explanation: "CB = CA + AB = (k - m) + 4m/3 = k + m/3." },
  { quizId: "bgcse-maths-t12-q2", questionId: "q4", answerIndex: 1, explanation: "PQ = OQ - OP = 6q - 2p." },
  { quizId: "bgcse-maths-t12-q2", questionId: "q5", answerIndex: 2, explanation: "PT is one quarter of PQ: (6q - 2p)/4 = 3q/2 - p/2." },
  { quizId: "bgcse-maths-t12-q2", questionId: "q6", answerIndex: 0, explanation: "OT = OP + PT = 2p + (3q/2 - p/2) = 3p/2 + 3q/2." },
  { quizId: "bgcse-maths-t12-q2", questionId: "q7", answerIndex: 1, explanation: "R is 2/5 of the way from A to B, giving OR = u + 2/5(v-u) = (3u+2v)/5." },
  { quizId: "bgcse-maths-t12-q2", questionId: "q8", answerIndex: 1, explanation: "2a = (4,2), so 2a - b = (4 - (-1), 2 - 3) = (5,-1)." },

  { quizId: "bgcse-maths-t12-q3", questionId: "q1", answerIndex: 0, explanation: "The diagonal position vector is the sum of the two adjacent side vectors: OB = a + c." },
  { quizId: "bgcse-maths-t12-q3", questionId: "q2", answerIndex: 1, explanation: "Opposite sides of a parallelogram are equal and parallel, so AB = OC = c." },
  { quizId: "bgcse-maths-t12-q3", questionId: "q3", answerIndex: 2, explanation: "AC = OC - OA = c - a." },
  { quizId: "bgcse-maths-t12-q3", questionId: "q4", answerIndex: 0, explanation: "OB = a+c and OC = c. Their midpoint is ((a+c)+c)/2 = a/2+c." },
  { quizId: "bgcse-maths-t12-q3", questionId: "q5", answerIndex: 1, explanation: "AM = 2/3 AB = 2c/3, so OM = OA + AM = a + 2c/3." },
  { quizId: "bgcse-maths-t12-q3", questionId: "q6", answerIndex: 1, explanation: "−3RS = −3(−a+2b) = 3a−6b = PQ, so they are parallel in opposite directions." },
  { quizId: "bgcse-maths-t12-q3", questionId: "q7", answerIndex: 1, explanation: "Magnitude = √(25 + 144) = √169 = 13." },
  { quizId: "bgcse-maths-t12-q3", questionId: "q8", answerIndex: 1, explanation: "AC = AB + BC = (2x+y)+(x-3y)=3x-2y." },

  { quizId: "bgcse-maths-t13-q1", questionId: "q1", answerIndex: 1, explanation: "Scale factor = large side ÷ small side = 8/5." },
  { quizId: "bgcse-maths-t13-q1", questionId: "q2", answerIndex: 1, explanation: "7.5 × 1.6 = 12 cm." },
  { quizId: "bgcse-maths-t13-q1", questionId: "q3", answerIndex: 2, explanation: "Area scale factor is the square of the linear scale factor: 3² = 9." },
  { quizId: "bgcse-maths-t13-q1", questionId: "q4", answerIndex: 2, explanation: "Area ratio is the square of the side ratio: 2²:5² = 4:25." },
  { quizId: "bgcse-maths-t13-q1", questionId: "q5", answerIndex: 2, explanation: "Volume ratio is the cube of the length ratio: 3³:4³ = 27:64." },
  { quizId: "bgcse-maths-t13-q1", questionId: "q6", answerIndex: 1, explanation: "Scale factor = 18/12 = 1.5, so 10 × 1.5 = 15 cm." },
  { quizId: "bgcse-maths-t13-q1", questionId: "q7", answerIndex: 1, explanation: "7.2 × 50,000 = 360,000 cm = 3.6 km." },
  { quizId: "bgcse-maths-t13-q1", questionId: "q8", answerIndex: 2, explanation: "Area factor = 1.5² = 2.25, so 24 × 2.25 = 54 cm²." },

  { quizId: "bgcse-maths-t13-q2", questionId: "q1", answerIndex: 1, explanation: "Area factor = (8/5)² = 2.56. 29.4 × 2.56 = 75.264 ≈ 75.3 cm²." },
  { quizId: "bgcse-maths-t13-q2", questionId: "q2", answerIndex: 1, explanation: "There are 637 ratio parts. 1274/637 = 2, so the smaller volume is 125 × 2 = 250 cm³." },
  { quizId: "bgcse-maths-t13-q2", questionId: "q3", answerIndex: 1, explanation: "Linear scale factor inner:outer = 10:15 = 2:3. Inner side = 24 × 2/3 = 16 cm." },
  { quizId: "bgcse-maths-t13-q2", questionId: "q4", answerIndex: 1, explanation: "Outer volume = 2880 cm³ and inner volume ≈ 853.3 cm³. Difference ≈ 2026.7 cm³ = 2030 cm³ to 3 s.f." },
  { quizId: "bgcse-maths-t13-q2", questionId: "q5", answerIndex: 2, explanation: "All linear dimensions use ratio 3:5, so volume ratio = 3³:5³ = 27:125." },
  { quizId: "bgcse-maths-t13-q2", questionId: "q6", answerIndex: 1, explanation: "Side ratio is the square root of the area ratio: 9:12 = 3:4." },
  { quizId: "bgcse-maths-t13-q2", questionId: "q7", answerIndex: 0, explanation: "Cube roots give the length ratio: ∛343:∛1000 = 7:10." },
  { quizId: "bgcse-maths-t13-q2", questionId: "q8", answerIndex: 2, explanation: "Linear factor = 15/6 = 2.5; volume factor = 2.5³ = 15.625. 96 × 15.625 = 1500 cm³." },

  { quizId: "bgcse-maths-t14-q1", questionId: "q1", answerIndex: 1, explanation: "By SOH, sin θ = opposite ÷ hypotenuse." },
  { quizId: "bgcse-maths-t14-q1", questionId: "q2", answerIndex: 0, explanation: "By TOA, tan θ = opposite ÷ adjacent." },
  { quizId: "bgcse-maths-t14-q1", questionId: "q3", answerIndex: 0, explanation: "Opposite = 10 sin 30° = 5 cm." },
  { quizId: "bgcse-maths-t14-q1", questionId: "q4", answerIndex: 1, explanation: "cos 40° = 12/h, so h = 12/cos40° ≈ 15.7 cm." },
  { quizId: "bgcse-maths-t14-q1", questionId: "q5", answerIndex: 0, explanation: "θ = sin⁻¹(8/17) ≈ 28.1°." },
  { quizId: "bgcse-maths-t14-q1", questionId: "q6", answerIndex: 1, explanation: "Height = 5 sin65° ≈ 4.53 m." },
  { quizId: "bgcse-maths-t14-q1", questionId: "q7", answerIndex: 0, explanation: "Height = 20 sin35° ≈ 11.5 m." },
  { quizId: "bgcse-maths-t14-q1", questionId: "q8", answerIndex: 0, explanation: "tan θ = 9/12 = 0.75, so θ ≈ 36.9°." },

  { quizId: "bgcse-maths-t14-q2", questionId: "q1", answerIndex: 0, explanation: "Cosine rule: c² = 7² + 10² - 2(7)(10)cos60° = 79, so c ≈ 8.89 cm." },
  { quizId: "bgcse-maths-t14-q2", questionId: "q2", answerIndex: 2, explanation: "cos C = (9²+11²-14²)/(2·9·11) = 6/198, so C ≈ 88.3°." },
  { quizId: "bgcse-maths-t14-q2", questionId: "q3", answerIndex: 2, explanation: "By the sine rule, b = 8 sin65° / sin40° ≈ 11.3 cm." },
  { quizId: "bgcse-maths-t14-q2", questionId: "q4", answerIndex: 1, explanation: "Area = 1/2 × 12 × 9 × sin55° ≈ 44.2 cm²." },
  { quizId: "bgcse-maths-t14-q2", questionId: "q5", answerIndex: 1, explanation: "Angles in a triangle total 180°, so C = 180 - 48 - 67 = 65°." },
  { quizId: "bgcse-maths-t14-q2", questionId: "q6", answerIndex: 2, explanation: "c = 9 sin65° / sin48° ≈ 10.976 cm ≈ 11.0 cm." },
  { quizId: "bgcse-maths-t14-q2", questionId: "q7", answerIndex: 2, explanation: "cos C = (5²+6²-7²)/(2·5·6) = 0.2, so C ≈ 78.5°." },
  { quizId: "bgcse-maths-t14-q2", questionId: "q8", answerIndex: 1, explanation: "The trigonometric area formula is A = 1/2 ab sin C." },

  { quizId: "bgcse-maths-t14-q3", questionId: "q1", answerIndex: 0, explanation: "A three-figure bearing is measured clockwise from north." },
  { quizId: "bgcse-maths-t14-q3", questionId: "q2", answerIndex: 1, explanation: "Reverse bearings differ by 180°: 046° + 180° = 226°." },
  { quizId: "bgcse-maths-t14-q3", questionId: "q3", answerIndex: 1, explanation: "310° - 180° = 130°." },
  { quizId: "bgcse-maths-t14-q3", questionId: "q4", answerIndex: 1, explanation: "From C, the bearings to A and B are 226° and 130°. Their difference is 96°." },
  { quizId: "bgcse-maths-t14-q3", questionId: "q5", answerIndex: 1, explanation: "Cosine rule gives AB ≈ √(500²+420²-2·500·420 cos96°) ≈ 686 m." },
  { quizId: "bgcse-maths-t14-q3", questionId: "q6", answerIndex: 1, explanation: "135° lies midway between east (090°) and south (180°), so it is south-east." },
  { quizId: "bgcse-maths-t14-q3", questionId: "q7", answerIndex: 2, explanation: "Reverse bearing = 275° - 180° = 095°." },
  { quizId: "bgcse-maths-t14-q3", questionId: "q8", answerIndex: 3, explanation: "Due west corresponds to a bearing of 270°." },

  { quizId: "bgcse-maths-t14-q4", questionId: "q1", answerIndex: 1, explanation: "Angles on a straight line sum to 180°, so MNP = 180° - 57.4° = 122.6°." },
  { quizId: "bgcse-maths-t14-q4", questionId: "q2", answerIndex: 1, explanation: "Cosine rule gives MP ≈ 15.7327 m ≈ 15.7 m." },
  { quizId: "bgcse-maths-t14-q4", questionId: "q3", answerIndex: 1, explanation: "Cosine rule gives OP ≈ 10.3369 m ≈ 10.3 m." },
  { quizId: "bgcse-maths-t14-q4", questionId: "q4", answerIndex: 0, explanation: "The perpendicular distance is MN sin38° = 6.2 sin38° ≈ 3.82 m." },
  { quizId: "bgcse-maths-t14-q4", questionId: "q5", answerIndex: 1, explanation: "Perpendicular distance = BC sin48° = 7.1 sin48° ≈ 5.28 m." },
  { quizId: "bgcse-maths-t14-q4", questionId: "q6", answerIndex: 1, explanation: "tan θ = 5.5/5.28, giving θ ≈ 46.2°." },
  { quizId: "bgcse-maths-t14-q4", questionId: "q7", answerIndex: 2, explanation: "Area = 1/2 × 19.8 × 10.4 × sin70° ≈ 96.8 cm²." },
  { quizId: "bgcse-maths-t14-q4", questionId: "q8", answerIndex: 1, explanation: "Height = 40 tan32° ≈ 25.0 m." },

  { quizId: "bgcse-maths-t15-q1", questionId: "q1", answerIndex: 1, explanation: "The angle at the centre is twice the angle at the circumference on the same arc, so 110°/2 = 55°." },
  { quizId: "bgcse-maths-t15-q1", questionId: "q2", answerIndex: 2, explanation: "The centre angle is twice the circumference angle: 2 × 47° = 94°." },
  { quizId: "bgcse-maths-t15-q1", questionId: "q3", answerIndex: 2, explanation: "The angle in a semicircle is 90°." },
  { quizId: "bgcse-maths-t15-q1", questionId: "q4", answerIndex: 1, explanation: "Angles in the same segment are equal." },
  { quizId: "bgcse-maths-t15-q1", questionId: "q5", answerIndex: 1, explanation: "Opposite angles in a cyclic quadrilateral sum to 180°, so 180° - 112° = 68°." },
  { quizId: "bgcse-maths-t15-q1", questionId: "q6", answerIndex: 2, explanation: "A tangent is perpendicular to the radius at the point of contact." },
  { quizId: "bgcse-maths-t15-q1", questionId: "q7", answerIndex: 0, explanation: "Equal chords subtend equal angles at the centre." },
  { quizId: "bgcse-maths-t15-q1", questionId: "q8", answerIndex: 2, explanation: "AB subtends a semicircle, so angle ACB = 90°." },

  { quizId: "bgcse-maths-t15-q2", questionId: "q1", answerIndex: 2, explanation: "The radius OC is perpendicular to the tangent at C." },
  { quizId: "bgcse-maths-t15-q2", questionId: "q2", answerIndex: 2, explanation: "Tangents drawn from the same external point are equal in length." },
  { quizId: "bgcse-maths-t15-q2", questionId: "q3", answerIndex: 1, explanation: "By the alternate segment theorem, the two angles are equal." },
  { quizId: "bgcse-maths-t15-q2", questionId: "q4", answerIndex: 1, explanation: "OA ⟂ TA, so TA = √(13² - 5²) = √144 = 12 cm." },
  { quizId: "bgcse-maths-t15-q2", questionId: "q5", answerIndex: 2, explanation: "The perpendicular bisects the chord. Half-chord = √(10² - 6²) = 8 cm, so full chord = 16 cm." },
  { quizId: "bgcse-maths-t15-q2", questionId: "q6", answerIndex: 0, explanation: "The perpendicular from the centre to a chord bisects that chord." },
  { quizId: "bgcse-maths-t15-q2", questionId: "q7", answerIndex: 0, explanation: "OA and OB are perpendicular to the tangents, so angle APB + angle AOB = 180°. Thus APB = 50°." },
  { quizId: "bgcse-maths-t15-q2", questionId: "q8", answerIndex: 2, explanation: "By the alternate segment theorem, angle ACB equals the tangent-chord angle, 62°." },

  { quizId: "bgcse-maths-t15-q3", questionId: "q1", answerIndex: 1, explanation: "Angles subtended by the same chord in the same segment are equal, so CBD = 55°." },
  { quizId: "bgcse-maths-t15-q3", questionId: "q2", answerIndex: 2, explanation: "The centre angle is twice the circumference angle: COD = 2 × 55° = 110°." },
  { quizId: "bgcse-maths-t15-q3", questionId: "q3", answerIndex: 2, explanation: "The tangent CE is perpendicular to radius CO, so ECO = 90°." },
  { quizId: "bgcse-maths-t15-q3", questionId: "q4", answerIndex: 1, explanation: "The angle at the circumference is half the angle at the centre: 110°/2 = 55°." },
  { quizId: "bgcse-maths-t15-q3", questionId: "q5", answerIndex: 3, explanation: "Opposite angles in a cyclic quadrilateral sum to 180°, so QRS = 125°." },
  { quizId: "bgcse-maths-t15-q3", questionId: "q6", answerIndex: 0, explanation: "Triangle SOQ is isosceles, so angle SQO = 35°. Since RS is parallel to OQ, angle QSR = 35°." },
  { quizId: "bgcse-maths-t15-q3", questionId: "q7", answerIndex: 0, explanation: "Angle at the circumference is half the angle at the centre: 74°/2 = 37°." },
  { quizId: "bgcse-maths-t15-q3", questionId: "q8", answerIndex: 1, explanation: "Opposite angles sum to 180°. Five parts = 180°, so one part = 36° and the smaller angle = 72°." },
];
