import type { SeedQuizAnswer } from "./seedQuizAnswers";

export const bgcseMathsTopic6To8SeedQuizAnswers: SeedQuizAnswer[] = [
  { quizId: "bgcse-maths-t06-q1", questionId: "q1", answerIndex: 2, explanation: "The common difference is 4, so 17 + 4 = 21." },
  { quizId: "bgcse-maths-t06-q1", questionId: "q2", answerIndex: 1, explanation: "A difference of 4 gives 4n. Adjusting to make the first term 5 gives 4n + 1." },
  { quizId: "bgcse-maths-t06-q1", questionId: "q3", answerIndex: 2, explanation: "4(50) + 1 = 201." },
  { quizId: "bgcse-maths-t06-q1", questionId: "q4", answerIndex: 0, explanation: "The common difference is -5, so the nth term is -5n + 47 = 47 - 5n." },
  { quizId: "bgcse-maths-t06-q1", questionId: "q5", answerIndex: 2, explanation: "5n + 2 = 102 gives 5n = 100, so n = 20." },
  { quizId: "bgcse-maths-t06-q1", questionId: "q6", answerIndex: 2, explanation: "The sequence increases by 5 each time, so the missing term is 17." },
  { quizId: "bgcse-maths-t06-q1", questionId: "q7", answerIndex: 1, explanation: "Each extra table adds 2 chairs. Starting with 4 chairs at n = 1 gives C = 2n + 2." },
  { quizId: "bgcse-maths-t06-q1", questionId: "q8", answerIndex: 1, explanation: "84 = 2n + 2, so 2n = 82 and n = 41." },

  { quizId: "bgcse-maths-t06-q2", questionId: "q1", answerIndex: 2, explanation: "The differences are 5, 7 and 9, so the next difference is 11. Thus 24 + 11 = 35." },
  { quizId: "bgcse-maths-t06-q2", questionId: "q2", answerIndex: 0, explanation: "n² + 2n gives 3, 8, 15 and 24 for n = 1, 2, 3 and 4." },
  { quizId: "bgcse-maths-t06-q2", questionId: "q3", answerIndex: 2, explanation: "10² + 2(10) = 100 + 20 = 120." },
  { quizId: "bgcse-maths-t06-q2", questionId: "q4", answerIndex: 0, explanation: "n² + n gives 2, 6, 12 and 20 for n = 1, 2, 3 and 4." },
  { quizId: "bgcse-maths-t06-q2", questionId: "q5", answerIndex: 1, explanation: "12 × 13 = 156, so n = 12." },
  { quizId: "bgcse-maths-t06-q2", questionId: "q6", answerIndex: 1, explanation: "The differences are -4, -6 and -8, so the next difference is -10. Thus 80 - 10 = 70." },
  { quizId: "bgcse-maths-t06-q2", questionId: "q7", answerIndex: 1, explanation: "100 - n(n + 1) gives 98, 94, 88 and 80 for n = 1, 2, 3 and 4." },
  { quizId: "bgcse-maths-t06-q2", questionId: "q8", answerIndex: 0, explanation: "100 - 50(51) = 100 - 2550 = -2450." },

  { quizId: "bgcse-maths-t06-q3", questionId: "q1", answerIndex: 2, explanation: "The differences are 3.5, 9.5, 15.5 and 21.5; they increase by 6. The next difference is 27.5, so the next term is 74.5." },
  { quizId: "bgcse-maths-t06-q3", questionId: "q2", answerIndex: 0, explanation: "Substituting n = 1, 2 and 3 into (6n² - 11n - 1)/2 gives -3, 0.5 and 10, matching the sequence." },
  { quizId: "bgcse-maths-t06-q3", questionId: "q3", answerIndex: 2, explanation: "Set (6n² - 11n - 1)/2 = 302. This gives 6n² - 11n - 605 = 0, whose positive solution is n = 11." },
  { quizId: "bgcse-maths-t06-q3", questionId: "q4", answerIndex: 1, explanation: "100 - n(n + 1) = -500 gives n(n + 1) = 600. Since 24 × 25 = 600, n = 24." },
  { quizId: "bgcse-maths-t06-q3", questionId: "q5", answerIndex: 2, explanation: "The pattern increases by 4, so T = 4n + 2. For n = 20, T = 82." },
  { quizId: "bgcse-maths-t06-q3", questionId: "q6", answerIndex: 0, explanation: "A common difference of 4 gives 4n, and adding 2 makes the first term 6." },
  { quizId: "bgcse-maths-t06-q3", questionId: "q7", answerIndex: 2, explanation: "Each term is double the previous term, so 24 × 2 = 48." },
  { quizId: "bgcse-maths-t06-q3", questionId: "q8", answerIndex: 1, explanation: "The terms are 3, 6, 12, 24, 48, 96, 192, so 192 is the 7th term." },

  { quizId: "bgcse-maths-t07-q1", questionId: "q1", answerIndex: 0, explanation: "Subtract 4 from both sides to get x > 6." },
  { quizId: "bgcse-maths-t07-q1", questionId: "q2", answerIndex: 1, explanation: "Divide both sides by 3 to get x ≤ 6." },
  { quizId: "bgcse-maths-t07-q1", questionId: "q3", answerIndex: 1, explanation: "Dividing by -2 reverses the inequality, giving x > -4." },
  { quizId: "bgcse-maths-t07-q1", questionId: "q4", answerIndex: 1, explanation: "Subtract 1 to get 4 ≤ 2x < 10, then divide by 2 to get 2 ≤ x < 5." },
  { quizId: "bgcse-maths-t07-q1", questionId: "q5", answerIndex: 2, explanation: "At least means greater than or equal to, so y ≥ 240." },
  { quizId: "bgcse-maths-t07-q1", questionId: "q6", answerIndex: 3, explanation: "At most means less than or equal to, so x + y ≤ 12." },
  { quizId: "bgcse-maths-t07-q1", questionId: "q7", answerIndex: 0, explanation: "140x + 175y ≤ 3850. Dividing by 35 gives 4x + 5y ≤ 110." },
  { quizId: "bgcse-maths-t07-q1", questionId: "q8", answerIndex: 0, explanation: "y ≤ 3/5(x + y). Multiplying by 5 and simplifying gives 2y ≤ 3x." },

  { quizId: "bgcse-maths-t07-q2", questionId: "q1", answerIndex: 1, explanation: "15x + 40y ≥ 240. Dividing by 5 gives 3x + 8y ≥ 48." },
  { quizId: "bgcse-maths-t07-q2", questionId: "q2", answerIndex: 1, explanation: "At most 12 means x + y ≤ 12." },
  { quizId: "bgcse-maths-t07-q2", questionId: "q3", answerIndex: 2, explanation: "At least 2 adults means y ≥ 2." },
  { quizId: "bgcse-maths-t07-q2", questionId: "q4", answerIndex: 0, explanation: "2800x + 4900y ≥ 1,372,000. Dividing by 700 gives 4x + 7y ≥ 1960." },
  { quizId: "bgcse-maths-t07-q2", questionId: "q5", answerIndex: 1, explanation: "No more than 410 means x + y ≤ 410." },
  { quizId: "bgcse-maths-t07-q2", questionId: "q6", answerIndex: 2, explanation: "At most 240 means y ≤ 240." },
  { quizId: "bgcse-maths-t07-q2", questionId: "q7", answerIndex: 0, explanation: "105x + 70y ≤ 6300. Dividing by 35 gives 3x + 2y ≤ 180." },
  { quizId: "bgcse-maths-t07-q2", questionId: "q8", answerIndex: 3, explanation: "Not less than 20 means y ≥ 20." },

  { quizId: "bgcse-maths-t07-q3", questionId: "q1", answerIndex: 0, explanation: "For (4,2), 2x + y = 10 and x + y = 6, so all four inequalities are satisfied." },
  { quizId: "bgcse-maths-t07-q3", questionId: "q2", answerIndex: 3, explanation: "Evaluate 3x + 5y at the vertices: 0, 15, 22 and 30. The maximum is 30." },
  { quizId: "bgcse-maths-t07-q3", questionId: "q3", answerIndex: 1, explanation: "At (4,5), 3x + 8y = 52 ≥ 48, x + y = 9 ≤ 12 and y = 5 ≥ 2." },
  { quizId: "bgcse-maths-t07-q3", questionId: "q4", answerIndex: 2, explanation: "R(A) = 240, R(B) = 260 and R(C) = 350, so C gives the greatest revenue." },
  { quizId: "bgcse-maths-t07-q3", questionId: "q5", answerIndex: 1, explanation: "For (13,11), 4x + 5y = 107 ≤ 110, 11 > 10 and 22 ≤ 39." },
  { quizId: "bgcse-maths-t07-q3", questionId: "q6", answerIndex: 2, explanation: "Testing the integer boundary points shows totals of 24 are possible, for example (13,11), while 25 would exceed the constraints." },
  { quizId: "bgcse-maths-t07-q3", questionId: "q7", answerIndex: 1, explanation: "To maximize y, use y = 240. Filling the 410-pupil capacity then gives x = 410 - 240 = 170." },
  { quizId: "bgcse-maths-t07-q3", questionId: "q8", answerIndex: 0, explanation: "The constraint y ≤ 2x - 10 with x + y = 50 requires x ≥ 20. Since rice is more expensive, the minimum cost occurs at the smallest allowed x, giving (20,30)." },

  { quizId: "bgcse-maths-t08-q1", questionId: "q1", answerIndex: 1, explanation: "Midpoint = ((2 + 8)/2, (-1 + 5)/2) = (5,2)." },
  { quizId: "bgcse-maths-t08-q1", questionId: "q2", answerIndex: 1, explanation: "Distance = √((4 - 1)² + (6 - 2)²) = √25 = 5." },
  { quizId: "bgcse-maths-t08-q1", questionId: "q3", answerIndex: 1, explanation: "Gradient = (15 - 3)/(4 - (-2)) = 12/6 = 2." },
  { quizId: "bgcse-maths-t08-q1", questionId: "q4", answerIndex: 2, explanation: "In y = mx + c, m is the gradient and c the y-intercept, so y = 3x - 4." },
  { quizId: "bgcse-maths-t08-q1", questionId: "q5", answerIndex: 0, explanation: "Substitute (2,-1): 3(-1) = 2 + d, so d = -5." },
  { quizId: "bgcse-maths-t08-q1", questionId: "q6", answerIndex: 1, explanation: "The gradient is (-4 - 5)/(3 - 0) = -3 and the y-intercept is 5, so y = -3x + 5." },
  { quizId: "bgcse-maths-t08-q1", questionId: "q7", answerIndex: 2, explanation: "On the x-axis y = 0. So 0 = 2x - 8 and x = 4." },
  { quizId: "bgcse-maths-t08-q1", questionId: "q8", answerIndex: 1, explanation: "Parallel lines have the same gradient, so the gradient is -0.5." },

  { quizId: "bgcse-maths-t08-q2", questionId: "q1", answerIndex: 2, explanation: "f(4) = 2(16) - 12 + 1 = 21." },
  { quizId: "bgcse-maths-t08-q2", questionId: "q2", answerIndex: 3, explanation: "f(-2) = 2(4) - 3(-2) + 1 = 8 + 6 + 1 = 15." },
  { quizId: "bgcse-maths-t08-q2", questionId: "q3", answerIndex: 2, explanation: "3x + 5 = 20 gives 3x = 15, so x = 5." },
  { quizId: "bgcse-maths-t08-q2", questionId: "q4", answerIndex: 0, explanation: "At x = 3, y = 3 × 4 × (5 - 6) = -12." },
  { quizId: "bgcse-maths-t08-q2", questionId: "q5", answerIndex: 1, explanation: "Set 3x + 5 = 2x + 11 to get x = 6. Then y = 23." },
  { quizId: "bgcse-maths-t08-q2", questionId: "q6", answerIndex: 2, explanation: "At x = 2, y = 2² + 2(2) = 4 + 4 = 8." },
  { quizId: "bgcse-maths-t08-q2", questionId: "q7", answerIndex: 0, explanation: "A product is zero when a factor is zero: x = 0, x + 1 = 0 or 5 - 2x = 0, giving 0, -1 and 2.5." },
  { quizId: "bgcse-maths-t08-q2", questionId: "q8", answerIndex: 2, explanation: "4³ - 3(4²) + 4 = 64 - 48 + 4 = 20." },

  { quizId: "bgcse-maths-t08-q3", questionId: "q1", answerIndex: 1, explanation: "Set x³ - 3x² + 4 = 4. Then x²(x - 3) = 0, so x = 0 or x = 3." },
  { quizId: "bgcse-maths-t08-q3", questionId: "q2", answerIndex: 2, explanation: "For y = x², the gradient is 2x. At x = 3, the gradient is 6." },
  { quizId: "bgcse-maths-t08-q3", questionId: "q3", answerIndex: 1, explanation: "Perpendicular gradients multiply to -1. Therefore 2 × m = -1, so m = -1/2." },
  { quizId: "bgcse-maths-t08-q3", questionId: "q4", answerIndex: 0, explanation: "Using y - 6 = -5(x - 2) gives y = -5x + 16." },
  { quizId: "bgcse-maths-t08-q3", questionId: "q5", answerIndex: 1, explanation: "For x = 2, y = 3(2) + 5 = 11, so (2,11) lies on the line." },
  { quizId: "bgcse-maths-t08-q3", questionId: "q6", answerIndex: 1, explanation: "The gradient is (12 - 4)/(5 - 1) = 2. Using (1,4), 4 = 2(1) + c, so c = 2." },
  { quizId: "bgcse-maths-t08-q3", questionId: "q7", answerIndex: 0, explanation: "If B = (x,y), then (1 + x)/2 = 4 and (-2 + y)/2 = 3, giving x = 7 and y = 8." },
  { quizId: "bgcse-maths-t08-q3", questionId: "q8", answerIndex: 0, explanation: "Roots -2, 1 and 4 correspond to factors x + 2, x - 1 and x - 4." },
];
